chore: windows check for line ending

diff --git a/.github/workflows/manual-windows.yml b/.github/workflows/manual-windows.yml
--- a/.github/workflows/manual-windows.yml
+++ b/.github/workflows/manual-windows.yml
@@ -20,6 +20,12 @@ jobs:
         with:
           version: stable
       - run: npm ci
+      - name: Check for CRLF line endings
+        run: |
+          if grep -rlI $'\r' . --exclude-dir={.git,node_modules}; then
+            echo "::error ::CRLF line endings found. Please convert to LF."
+            exit 1
+          fi
       - run: npm run prettier:check
       - run: npm run lint
       - run: npm run compile
